#[derive(Eq, PartialEq, Hash, Debug)]
pub enum MessageAttribute {
    MappedAddress = 0,
    ResponseAddress,
    ChangeRequest,
    SourceAddress,
    ChangedAddress,
    Username,
    Password,
    MessageIntegrity,
    ErrorCode,
    UnknownAttributes,
    ReflectedFrom,
    ChannelNumber,
    Lifetime,
    AlternateServer,
    MagicCookie,
    Bandwidth,
    DestinationAddress,
    XorPeerAddress,
    Data,
    Realm,
    Nonce,
    XorRelayedAddress,
    RequestedAddressType,
    EvenPort,
    RequestedTransport,
    DontFragment,
    XorMappedAddress,
    ReservationToken,
    Priority,
    UseCandidate,
    Padding,
    ResponsePort,
    XorReflectedFrom,
    Icmp,
    XVovidaXorMappedAddress,
    XVovidaXorOnly,
    Software,
    CacheTimeout,
    Fingerprint,
    IceControlled,
    IceControlling,
    ResponseOrigin,
    OtherAddress,
    XVovidaSecondaryAddress,
    ConnectionRequestBinding,
    BindingChange
}

impl MessageAttribute {
    pub fn from_u16(i: u16) -> MessageAttribute {
        match i {
            0x0001 => MessageAttribute::MappedAddress,
            0x0002 => MessageAttribute::ResponseAddress,
            0x0003 => MessageAttribute::ChangeRequest,
            0x0004 => MessageAttribute::SourceAddress,
            0x0005 => MessageAttribute::ChangedAddress,
            0x0006 => MessageAttribute::Username,
            0x0007 => MessageAttribute::Password,
            0x0008 => MessageAttribute::MessageIntegrity,
            0x0009 => MessageAttribute::ErrorCode,
            0x000A => MessageAttribute::UnknownAttributes,
            0x000B => MessageAttribute::ReflectedFrom,
            0x000c => MessageAttribute::ChannelNumber,
            0x000D => MessageAttribute::Lifetime,
            0x000E => MessageAttribute::AlternateServer,
            0x000F => MessageAttribute::MagicCookie,
            0x0010 => MessageAttribute::Bandwidth,
            0x0011 => MessageAttribute::DestinationAddress,
            0x0012 => MessageAttribute::XorPeerAddress,
            0x0013 => MessageAttribute::Data,
            0x0014 => MessageAttribute::Realm,
            0x0015 => MessageAttribute::Nonce,
            0x0016 => MessageAttribute::XorRelayedAddress,
            0x0017 => MessageAttribute::RequestedAddressType,
            0x0018 => MessageAttribute::EvenPort,
            0x0019 => MessageAttribute::RequestedTransport,
            0x001a => MessageAttribute::DontFragment,
            0x0020 => MessageAttribute::XorMappedAddress,
            0x0022 => MessageAttribute::ReservationToken,
            0x0024 => MessageAttribute::Priority,
            0x0025 => MessageAttribute::UseCandidate,
            0x0026 => MessageAttribute::Padding,
            0x0027 => MessageAttribute::ResponsePort,
            0x0028 => MessageAttribute::XorReflectedFrom,
            0x0030 => MessageAttribute::Icmp,
            0x8020 => MessageAttribute::XVovidaXorMappedAddress,
            0x8021 => MessageAttribute::XVovidaXorOnly,
            0x8022 => MessageAttribute::Software,
            0x8023 => MessageAttribute::AlternateServer,
            0x8027 => MessageAttribute::CacheTimeout,
            0x8028 => MessageAttribute::Fingerprint,
            0x8029 => MessageAttribute::IceControlled,
            0x802A => MessageAttribute::IceControlling,
            0x802B => MessageAttribute::ResponseOrigin,
            0x802C => MessageAttribute::OtherAddress,
            0x8050 => MessageAttribute::XVovidaSecondaryAddress,
            0xC001 => MessageAttribute::ConnectionRequestBinding,
            0xC002 => MessageAttribute::BindingChange,
            _      => panic!("Unknown message attribute")
        }
    }

    pub fn to_u16(self) -> u16 {
        match self {
            MessageAttribute::MappedAddress => 0x0001,
            MessageAttribute::ResponseAddress => 0x0002,
            MessageAttribute::ChangeRequest => 0x0003,
            MessageAttribute::SourceAddress => 0x0004,
            MessageAttribute::ChangedAddress => 0x0005,
            MessageAttribute::Username => 0x0006,
            MessageAttribute::Password => 0x0007,
            MessageAttribute::MessageIntegrity => 0x0008,
            MessageAttribute::ErrorCode => 0x0009,
            MessageAttribute::UnknownAttributes => 0x000A,
            MessageAttribute::ReflectedFrom => 0x000B,
            MessageAttribute::ChannelNumber => 0x000c,
            MessageAttribute::Lifetime => 0x000D,
            MessageAttribute::MagicCookie => 0x000F,
            MessageAttribute::Bandwidth => 0x0010,
            MessageAttribute::DestinationAddress => 0x0011,
            MessageAttribute::XorPeerAddress => 0x0012,
            MessageAttribute::Data => 0x0013,
            MessageAttribute::Realm => 0x0014,
            MessageAttribute::Nonce => 0x0015,
            MessageAttribute::XorRelayedAddress => 0x0016,
            MessageAttribute::RequestedAddressType => 0x0017,
            MessageAttribute::EvenPort => 0x0018,
            MessageAttribute::RequestedTransport => 0x0019,
            MessageAttribute::DontFragment => 0x001a,
            MessageAttribute::XorMappedAddress => 0x0020,
            MessageAttribute::ReservationToken => 0x0022,
            MessageAttribute::Priority => 0x0024,
            MessageAttribute::UseCandidate => 0x0025,
            MessageAttribute::Padding => 0x0026,
            MessageAttribute::ResponsePort => 0x0027,
            MessageAttribute::XorReflectedFrom => 0x0028,
            MessageAttribute::Icmp => 0x0030,
            MessageAttribute::XVovidaXorMappedAddress => 0x8020,
            MessageAttribute::XVovidaXorOnly => 0x8021,
            MessageAttribute::Software => 0x8022,
            MessageAttribute::AlternateServer => 0x8023,
            MessageAttribute::CacheTimeout => 0x8027,
            MessageAttribute::Fingerprint => 0x8028,
            MessageAttribute::IceControlled => 0x8029,
            MessageAttribute::IceControlling => 0x802A,
            MessageAttribute::ResponseOrigin => 0x802B,
            MessageAttribute::OtherAddress => 0x802C,
            MessageAttribute::XVovidaSecondaryAddress => 0x8050,
            MessageAttribute::ConnectionRequestBinding => 0xC001,
            MessageAttribute::BindingChange => 0xC002,
        }
    }
}
